"""add medication log scheduled time

Revision ID: 05b519a140f9
Revises: a4c17b795eb2
Create Date: 2025-07-31 02:57:03.891233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b519a140f9'
down_revision: Union[str, None] = 'a4c17b795eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_log', sa.Column('scheduled_time', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication_log', 'scheduled_time')
    # ### end Alembic commands ###
