"""add vital group

Revision ID: 081ce14e4130
Revises: 7a577a619bd4
Create Date: 2025-07-28 02:44:10.554001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081ce14e4130'
down_revision: Union[str, None] = '7a577a619bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vitals', sa.Column('vital_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vitals', 'vital_group')
    # ### end Alembic commands ###
