"""add_color_to_care_task_categories

Revision ID: 39ec29f00e94
Revises: ce9b27dfa0a0
Create Date: 2025-08-10 02:31:22.927185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ec29f00e94'
down_revision: Union[str, None] = 'ce9b27dfa0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_task_category', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###
    
    # Set default colors for existing categories
    connection = op.get_bind()
    
    # Define default colors for the default categories
    default_colors = {
        'nutrition': '#ff6b6b',    # Red for nutrition
        'bathroom': '#4ecdc4',     # Teal for bathroom
        'vitals': '#45b7d1',       # Blue for vitals  
        'therapy': '#96ceb4'       # Green for therapy
    }
    
    # Update existing categories with their default colors
    for category_name, color in default_colors.items():
        connection.execute(
            sa.text("UPDATE care_task_category SET color = :color WHERE name = :name"),
            {"color": color, "name": category_name}
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_task_category', 'color')
    # ### end Alembic commands ###
