"""add_care_task_tables

Revision ID: 7613470f16fb
Revises: 05b519a140f9
Create Date: 2025-08-10 00:40:13.348461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7613470f16fb'
down_revision: Union[str, None] = '05b519a140f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_task_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('care_task_id', sa.Integer(), nullable=False),
    sa.Column('cron_expression', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_task_id'], ['care_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('care_task_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('care_task_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('scheduled_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_early', sa.Boolean(), nullable=False),
    sa.Column('completed_late', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_task_id'], ['care_task.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['care_task_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('care_task_log')
    op.drop_table('care_task_schedule')
    op.drop_table('care_task')
    # ### end Alembic commands ###
