"""initial tables3

Revision ID: 7a577a619bd4
Revises: bd0fb09cdb8c
Create Date: 2025-07-27 18:21:05.142924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a577a619bd4'
down_revision: Union[str, None] = 'bd0fb09cdb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_pressure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('map', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_changed', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('useful_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('start_data_id', sa.Integer(), nullable=True),
    sa.Column('end_data_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('spo2_min', sa.Integer(), nullable=True),
    sa.Column('bpm_min', sa.Integer(), nullable=True),
    sa.Column('spo2_max', sa.Integer(), nullable=True),
    sa.Column('bpm_max', sa.Integer(), nullable=True),
    sa.Column('spo2_alarm_triggered', sa.Boolean(), nullable=True),
    sa.Column('hr_alarm_triggered', sa.Boolean(), nullable=True),
    sa.Column('external_alarm_triggered', sa.Boolean(), nullable=True),
    sa.Column('oxygen_used', sa.Boolean(), nullable=True),
    sa.Column('oxygen_highest', sa.Float(), nullable=True),
    sa.Column('oxygen_unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pulse_ox_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('pa', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('motion', sa.String(), nullable=True),
    sa.Column('spo2_alarm', sa.String(), nullable=True),
    sa.Column('hr_alarm', sa.String(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('temperature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('skin_temp', sa.Float(), nullable=True),
    sa.Column('body_temp', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventilator_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('pin', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_activity', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('vital_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_change_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_alarms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('pin', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_activity', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['monitoring_alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_alarms')
    op.drop_table('equipment_change_log')
    op.drop_table('vitals')
    op.drop_table('ventilator_alerts')
    op.drop_table('temperature')
    op.drop_table('settings')
    op.drop_table('pulse_ox_data')
    op.drop_table('monitoring_alerts')
    op.drop_table('equipment')
    op.drop_table('blood_pressure')
    # ### end Alembic commands ###
