"""add_equipment_quantity_and_scheduled_replacement

Revision ID: a963cbd388da
Revises: 081ce14e4130
Create Date: 2025-07-30 00:32:24.489284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a963cbd388da'
down_revision: Union[str, None] = '081ce14e4130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('equipment', sa.Column('scheduled_replacement', sa.Boolean(), nullable=False))
    op.alter_column('equipment', 'last_changed',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('equipment', 'useful_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment', 'useful_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipment', 'last_changed',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('equipment', 'scheduled_replacement')
    op.drop_column('equipment', 'quantity')
    # ### end Alembic commands ###
